import { AssetOption } from "src/types";

export const slimesAssets: AssetOption[] = [
  {
    id: 0,
    name: "Original Artwork",
    lowResPath: "images/slimes/low-res",
    highResPath: "images/slimes/high-res",
    width: 64,
    height: 64,
    className: "rounded-lg border border-scum-black/30",
    extension: "jpg",
  },
  {
    id: 1,
    name: "Desktop Wallpaper",
    lowResPath: "images/wallpapers/desktop-display",
    highResPath: "images/wallpapers/desktop",
    width: 132,
    height: 79,
    className: "",
    extension: "png",
  },
  {
    id: 2,
    name: "X Wallpaper",
    lowResPath: "images/wallpapers/banner",
    highResPath: "images/wallpapers/banner",
    width: 192,
    height: 64,
    className: "scale-75 lg:scale-90 rounded-lg border border-scum-black/30",
    extension: "png",
  }, 
  {
    id: 3,
    name: "Mobile Wallpaper",
    lowResPath: "images/wallpapers/mobile-display",
    highResPath: "images/wallpapers/mobile",
    width: 50,
    height: 83,
    className: "",
    extension: "png",
  }, 
  //tiny denise
  {
    isTinyDenise: true,
    id: 4,
    name: "Original Artwork",
    lowResPath: "images/tiny-denise/low-res",
    highResPath: "images/tiny-denise/high-res",
    path:"images/tiny-assets",

    width: 64,
    height: 64, 
    extension: "jpg",
    className: "rounded-lg border border-scum-black/30",
  },
  {
    isTinyDenise: true,
    id: 5,
    name: "PFP",
    lowResPath: "images/tiny-denise/low-res",
    highResPath: "images/tiny-denise/high-res",
    path:"images/tiny-assets",

    width: 64,
    height: 64, 
    extension: "jpg",
    className: "rounded-lg border border-scum-black/30",
  },
  {
    isTinyDenise: true,
    id: 6,
    name: "X Wallpaper",
    lowResPath: "images/tiny-denise/low-res",
    highResPath: "images/tiny-denise/high-res",
    path:"images/tiny-assets",

    width: 192,
    height: 64, 
    extension: "jpg",
    className: "scale-75 lg:scale-90 rounded-lg border border-scum-black/30",
  }, 
  {
    isTinyDenise: true,
    id: 7,
    name: "Mobile Wallpaper",
    lowResPath: "images/tiny-denise/low-res",
    highResPath: "images/tiny-denise/high-res",
    path:"images/tiny-assets",

    width: 50,
    height: 83, 
    extension: "jpg",
    className: "scale-75 lg:scale-90 rounded-lg border border-scum-black/30",
  }, 
];